// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygkhmcnpjjvmbrbyybik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlna2htY25wamp2bWJyYnl5YmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNzI3NTUsImV4cCI6MjA1MzY0ODc1NX0.PCjfCJDHt_AdO7gomtkqhNZrFRB5zHpYo6JcJ52uB60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);