name: Deploy via SFTP

on:
  push:
    branches:
      - main  # Trigger deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy via SCP (no rsync)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SFTP_SSH_KEY }}
          port: ${{ secrets.FTP_PORT || 22 }}
          source: "dist/*"
          target: "/public_html/"
      

